#! /usr/bin/gforth

include cdump.fs

( compute 2n!/n!*n! )

19 constant N-1
20 constant N
40 constant N2
variable numerators N-1 cells allot
variable denominators N-1 cells allot

: nummul ( -- )
( multiplies 20 bytes from numerators - double precision )
1.
20 0 do
  numerators i + c@ 1 m*/
loop
;

: denommul ( -- )
( multiplies 20 bytes from denominators - single precision )
1
20 0 do
  denominators i + c@ *
loop
;

: set_numerators ( num -- )
( store n+1-2n to numerators )
dup dup
0 do
  i + 1+
  numerators i + c!
  dup
loop
2drop
;

: set_denominators ( num -- )
( store 1-n to denominators )
dup dup
0 do
  i 1+
  denominators i + c!
loop
2drop
;

: factorise ( num  -- )
( reduce size of numbers generated by cancelling out multiples of denominator elements )
dup
0 do
  0 do
    denominators i + c@ 
    dup 1 =
    if
      drop
    else
      numerators j + c@ 
      swap 2dup mod 0=
      if
        /
        numerators j + c!
        1 denominators i + c!
      then
    then
  loop
loop
;

: pe015 ( -- )
  20 set_numerators
  20 set_denominators
  20 factorise
  nummul 1 denommul m*/
  d. cr
;

pe015
bye
