[package]
name = "pe024"
version = "0.1.0"
authors = ["Bob Wilkinson <bob@fourtheye.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
