#!/bin/bash
#MAX=25
#
pushd ../ocaml >/dev/null
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 21 22 23 24; do
	x=$(printf "%03d" $i)
	pushd pe$x >/dev/null
	printf "../../scripts/time2 ocaml pe %03d ../run_dune ''\n" $i | bash
	popd >/dev/null
done
popd >/dev/null
#
for i in 20 25; do
  printf "./time1 ocaml ../ocaml/pe %03d '' .native\n" $i | bash
done
