#!/bin/bash
mkdir -p ../output
declare -a compiled
compiled=(ada c c++ erlang go haskell java ocaml)
#lscpu | grep ^Architecture
#Architecture:                       aarch64
# lscpu | grep Architectur
# Architecture:        armv7l
if grep --quiet -E "ARMv[1-9]" /proc/cpuinfo
then
  compiled=(asm32 ${compiled[@]})
fi
echo compiled is $compiled
for lang in ${compiled[@]}
do
  echo lang is $lang
  make -C ../$lang
  ./time$lang
  mv data.$lang.* ../output
  make -C ../$lang clean
done
#
declare -a scripts
scripts=(elixir forth javascript lua perl python racket ruby tcl typescript)
for lang in ${scripts[@]}
do
  echo lang is $lang
  ./time$lang
  mv data.$lang.* ../output
done
#
for lang in rust
do
  echo lang is $lang
  cd ../$lang
  ./build.sh
  ./runall.sh
  mv data.$lang.* ../output
  ./clean.sh
  cd -
done
