#!/bin/bash
mkdir -p ../output
declare -a compiled
#compiled=(c c++ erlang go java ocaml)
compiled=(c c++ erlang go java)
if grep --quiet -E "ARMv[1-9]" /proc/cpuinfo
then
  compiled=(asm ${compiled[@]})
fi
echo compiled is $compiled
for lang in ${compiled[@]}
do
  echo lang is $lang
  make -C ../$lang
  ./time$lang
  mv data.$lang.* ../output
  make -C ../$lang clean
done
#
declare -a scripts
scripts=(forth javascript perl python racket)
for lang in ${scripts[@]}
do
  echo lang is $lang
  ./time$lang
  mv data.$lang.* ../output
done
#
for lang in rust
do
  echo lang is $lang
  cd ../$lang
  ./build.sh
  ./runall.sh
  mv data.$lang.* ../output
  ./clean.sh
  cd -
done
